name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        os_name: [linux, windows, macos]
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, aarch64-apple-darwin]
        include:
          - os: ubuntu-latest
            os_name: linux
          - os: windows-latest
            os_name: windows
          - os: macos-latest
            os_name: macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install openssl
          export OPENSSL_DIR=$(brew --prefix openssl)
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$OPENSSL_DIR/lib/pkgconfig
        shell: bash

      - name: Install pkg-config on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y pkg-config libssl-dev

      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --bins
        env:
          OPENSSL_DIR: ${{ env.OPENSSL_DIR }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
        continue-on-error: true

      - name: Upload binaries
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.os }}-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/sc
            target/${{ matrix.target }}/release/sc-serve

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Publish to Crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries-ubuntu-latest-x86_64-unknown-linux-gnu

      - name: Build Docker image
        run: docker build -t sc-serve .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag sc-serve ghcr.io/${{ github.repository }}/sc-serve:latest
          docker push ghcr.io/${{ github.repository }}/sc-serve:latest